---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodeapp-deployment
      lables:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp-deployment
          image: sunnyramagiri/nodeapp:latest # it's docker hub user name
          ports:
            - containerPort: 3000
...


---              
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
...
